### ISSUE TITLE
not formatting

### ISSUE THREAD

**Issue by JankleDev** [bajrangCoder/PHPPrettifier#2]
It doesn't formats the code. i don't know it just doesn't but sometimes it does like 1 % of the time. reinstalling doesn't fixs it.

**Comment by JankleDev** [comment]
if you want to know anything tell me

**Comment by bajrangCoder** [comment]
Can you share a screen recording

**Comment by JankleDev** [comment]
Uploading Screenrecording_20230731_095521.mp4…

here

**Comment by JankleDev** [comment]
https://youtu.be/hfEIh-tdfNA

here's yt link in case video doesn't uploads here

**Comment by bajrangCoder** [comment]
Ok can you provide your source which you are trying to format because it's works on my sources.
Provide code through any pastebin service.

**Comment by JankleDev** [comment]
https://pastebin.com/Zje6AAwi

i tried formatting multiple php files but it doesn't seems to work.

**Comment by bajrangCoder** [comment]
Ohh, it's working buts it's slow on large files 
I will improve it in next update.

**Comment by bajrangCoder** [comment]
I have patched this issue in `v1.0.2`
Check it and let me know if issue persists
